base_score: 0.5
booster: gbtree
callbacks: null
colsample_bylevel: 1
colsample_bynode: 1
colsample_bytree: 0.5
early_stopping_rounds: null
enable_categorical: false
eval_metric: null
gamma: 0
gpu_id: -1
grow_policy: depthwise
importance_type: null
interaction_constraints: ''
learning_rate: 0.1
max_bin: 256
max_cat_to_onehot: 4
max_delta_step: 0
max_depth: 3
max_leaves: 0
min_child_weight: 1
missing: 0
model_class: XGBClassifier
monotone_constraints: ()
n_estimators: 100
n_jobs: 0
num_parallel_tree: 1
objective: binary:logistic
predictor: auto
random_state: 42
reg_alpha: 0
reg_lambda: 10
sampling_method: uniform
scale_pos_weight: 3
seed: 42
subsample: 0.9
tree_method: exact
use_label_encoder: false
validate_parameters: 1
verbosity: null
