target: Churn_Value
features:
  - Zip_Code,
  - Latitude,
  - Longitude,
  - Tenure_Months,
  - Monthly_Charges,
  - Total_Charges,
  - Gender_Male,
  - Senior_Citizen_Yes,
  - Partner_Yes,
  - Dependents_Yes,
  - Phone_Service_Yes,
  - Multiple_Lines_No_phone_service,
  - Multiple_Lines_Yes,
  - Internet_Service_Fiber_optic,
  - Internet_Service_No,
  - Online_Security_No_internet_service,
  - Online_Security_Yes,
  - Online_Backup_No_internet_service,
  - Online_Backup_Yes,
  - Device_Protection_No_internet_service,
  - Device_Protection_Yes,
  - Tech_Support_No_internet_service,
  - Tech_Support_Yes,
  - Streaming_TV_No_internet_service,
  - Streaming_TV_Yes,
  - Streaming_Movies_No_internet_service,
  - Streaming_Movies_Yes,
  - Contract_One_year,
  - Contract_Two_year,
  - Paperless_Billing_Yes,
  - Payment_Method_Credit_card_automatic,
  - Payment_Method_Electronic_check,
  - Payment_Method_Mailed_check